<form enctype="multipart/form-data" method="post" action="<?php echo App::config('url') ?>Index/newPost">

    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content">
        Send this file: <input name="userfile" type="file" />
    </div>


    <button type="submit" class="btn btn-primary">Save</button>

</form>


<?php foreach ($posts as $post): ?>
    <p>
        <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
            <?= htmlspecialchars($post->getContent()) ?>
        </a>
        <?php if($post->getImageloc() != NULL) : ?>
        <img src="<?php echo App::config('url').'img/'.$post->getImageloc()?>">
        <?php endif; ?>
    </p>

<?php endforeach; ?>
