<div class="container">
<form enctype="multipart/form-data" method="post" action="<?php echo App::config('url') ?>Index/newPost">

    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content">
        Send this file: <input name="userfile" type="file" />
    </div>


    <button type="submit" class="btn btn-primary">Save</button>

</form>

<?php foreach ($posts as $post): ?>
    <div class="row">
    <p>
        <div class="six columns">
        <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId()?> ">
            <?= htmlspecialchars($post->getContent().' '.date('d.m.Y H:i',strtotime($post->getTime())).' '.$post->getCommentcount() ) ?>
        </a></p>
        </div>
        <?php if($post->getImageloc() != NULL) : ?>
        <div class="six columns">
        <img src="<?php echo App::config('url').'img/'.$post->getImageloc()?>" style="width: 50%; height: auto;">
        </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>